export const CHANGED_OPTIONS = "CHANGED_OPTIONS";
export const CHANGED_CREATE_PRODUCT = "CHANGED_CREATE_PRODUCT";
export const CHANGED_X = "CHANGED_X";
export const CHANGED_Y = "CHANGED_Y";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const SELECT_PRODUCT = "SELECT_PRODUCT";
